// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OkulYönetim.Entity.EntityFramework.Context;

#nullable disable

namespace OkulYönetim.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221213205029_userclasspassedadded")]
    partial class userclasspassedadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OkulYönetim.Entity.concrete.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DersID")
                        .HasColumnType("int");

                    b.Property<float>("NoteValue")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DersID");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Branch = "Admin",
                            Email = "adminuser123@gmail.com",
                            Name = "AmidnUser",
                            PasswordHash = new byte[] { 29, 72, 91, 139, 190, 66, 142, 210, 181, 69, 201, 16, 68, 83, 49, 177, 185, 183, 61, 15, 150, 130, 60, 63, 251, 85, 100, 179, 223, 201, 235, 2 },
                            PasswordSalt = new byte[] { 64, 10, 50, 4, 29, 210, 96, 161, 80, 59, 147, 20, 31, 102, 11, 190, 168, 208, 231, 159, 162, 173, 222, 96, 55, 122, 207, 60, 155, 211, 70, 66, 208, 196, 3, 45, 165, 115, 101, 62, 9, 77, 20, 155, 199, 97, 209, 241, 27, 98, 50, 95, 18, 235, 64, 105, 134, 172, 78, 187, 213, 118, 119, 178 },
                            Surname = "AmidnUser",
                            UserRoleId = 4
                        });
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.UserClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.ToTable("UserClasses");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.UserDers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Dersid")
                        .HasColumnType("int");

                    b.Property<int>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Dersid");

                    b.HasIndex("Userid");

                    b.ToTable("UserDers");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.Note", b =>
                {
                    b.HasOne("OkulYönetim.Entity.concrete.Ders", "Dersler")
                        .WithMany()
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OkulYönetim.Entity.concrete.User", "Users")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dersler");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.User", b =>
                {
                    b.HasOne("OkulYönetim.Entity.concrete.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.UserClass", b =>
                {
                    b.HasOne("OkulYönetim.Entity.concrete.Class", "Classes")
                        .WithMany("userClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OkulYönetim.Entity.concrete.User", "Users")
                        .WithMany("userClasses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.UserDers", b =>
                {
                    b.HasOne("OkulYönetim.Entity.concrete.Ders", "Dersler")
                        .WithMany("userDers")
                        .HasForeignKey("Dersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OkulYönetim.Entity.concrete.User", "Users")
                        .WithMany("userDers")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dersler");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.Class", b =>
                {
                    b.Navigation("userClasses");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.Ders", b =>
                {
                    b.Navigation("userDers");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.User", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("userClasses");

                    b.Navigation("userDers");
                });

            modelBuilder.Entity("OkulYönetim.Entity.concrete.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
